In [13]:
import torch
x=torch.arange(4.0)
x.requires_grad_(True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [14]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [20]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [21]:
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [26]:
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=b*100
    return c
a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()
a.grad==d/a

tensor(True)